### ISSUE TITLE
using amqpc.serve with an asynchronous function

### ISSUE THREAD

**Issue by servo1** [ttab/amqp-as-promised#5]
This question is likely due to my lack of understanding of coffee script and your examples but I've scoured the web and docs to no avail and translated the coffee script files to javascript.  

I am trying to return data from a mongoose query as a result of amqpc.serve as follows:
amqpc.serve('sipc', "/shop/products", function(msg, headers, del, progress) {
	products.find().limit(10).exec(function(res, res1) {
		return res1;
	});
});
The call get's made but I am assuming since the products.find (mongoose model) is asynchronous is causing the issue.
Any assistance on this would be greatly appreciated.

**Comment by algesten** [comment]
you need to wrap the result in a promise. that way the library will wait for the value.

```
return new Promise((rs) => {
 rs(result)
})
```

**Comment by servo1** [comment]
Beautiful, simple, thank you!
